### PR TITLE
fix: Windows interop

### PR DESCRIPTION
**Pull request by richardschneider**

### CODE REVIEW

**Comment by richardschneider** [comment]
@diasdavid needs your `Flow` magic.

**Comment by richardschneider** [comment]
@diasdavid I don't think flow is setup correctly.  I simply told it ignore `node_modules`.  You are the one with magic to make projects work with in.  Is this really buying you anything?

**Comment by diasdavid** [comment]
I defer that question to @dignifiedquire, the `flow` evangelist around here (I do like types though, but definitely haven't made a decision to use flow as a community).

**Comment by richardschneider** [comment]
@dignifiedquire No need for you attention.  I rtfm on `flow` and made the fixes.

**Comment by richardschneider** [comment]
@diasdavid CI is passing.  Can you release it now.  I need to rebuild ipfs-repo next!

**Pull request merged**
